### ISSUE TITLE
Highlight on emojis

### ISSUE THREAD

**Issue by JacobLey** [meilisearch/MeiliSearch#1368]
**Describe the bug**
Using Meilisearch's `_matches` and `_formattedInfo` of the response should show the searcher the exact text that was found in the search.

I have found that _mostly_ works, but appears to break when an emoji is in the middle of a word. Note to the best of my knowledge the actual search results are still correct, it is just over-highlighting the results.

**To Reproduce**

1) Create an index with a searchable attribute `text`.
2) Upload a document with the text `Go💼od luck.`
3) Perform the following search on the index:
```
{
  "q": "Go💼",
  "attributesToHighlight": ["text"],
  "matches": true
}
```
4) View results:
```
{
  "hits": [
    {
      "text": "Go💼od luck.",
      "_formatted": {
        "text": "<em>Go💼od lu</em>ck."
      },
      "_matchesInfo": {
        "text": [
          {
            "start": 0,
            "length": 11
          }
        ]
      }
    }
  ],
  "offset": 0,
  "limit": 20,
  "nbHits": 1,
  "exhaustiveNbHits": false,
  "processingTimeMs": 1,
  "query": "Go💼"
}
```

**Expected behavior**

I would expect the same document to be returned, but the `<em>` highlighting should only extend to the briefcase emoji (e.g. `"text": "<em>Go💼</em>od luck."`, and the matchesInfo length should be 6 (2 bytes for plain text + 4 for emoji in UTF-8)

**Additional context**
Running 0.19.0
I know that is a version behind, but I don't see anything notable in the changelog that I would expect to resolve this: https://github.com/meilisearch/MeiliSearch/releases

Note I am _not_ able to recreate the issue when the text is something like `💼Good💼 luck.` and I search for part or all of that word (e.g. `💼Go` or `💼Good💼`).

**Comment by curquiza** [comment]
Hello, thanks for the report, we will see if it's possible to fix it in the next release.

**Comment by curquiza** [comment]
@JacobLey, it's impossible for the search engine to highlight correctly emojis. The search engine de-unicodes the string and cannot work with emoji in the string when applying the highlight.
The next version will just not highlight any emoji then. Sorry for the inconvenience.

@CaroFG and @meilisearch/docs-team, it might interest you.

**Comment by JacobLey** [comment]
> will just not highlight any emoji then
That sounds fair to me.

This issue wasn't at all breaking for me, it was just that the behavior felt non-deterministic. I would agree not highlighting an emoji (is "highlighting" even a thing emojis actually support?) is preferable to over-highlighting. 

In my personal use case I don't really expect emojis to be used directly in search (although the result sets most definitely can contain them), I was just testing edge cases and ensuring I was properly interpreting `_matchesInfo`

**Comment by curquiza** [comment]
Sorry for the confusion: we thought we were not able to fix this, but we were 🥲 It will be highlighted but the complete word, here `Go💼od` instead of just `Go💼`

Sorry again for the confusion! This fix will be present in v0.21.0!
@meilisearch/docs-team @CaroFG again!

**Comment by curquiza** [comment]
Fixed by #1457

**Comment by MarinPostma** [comment]
reopening since this is not fixed: the example given in https://github.com/meilisearch/MeiliSearch/issues/1173 still isn't working (this is basically the same issue). The fix provided by @ManyTheFish does not addresses the issue since the length of the highlight returned by the matcher could be on a character boundary, but not the right boundary. This is what happens in the example from #1173.

@Kerollmops @ManyTheFish, milli must return an accurate length since we can't guess the correct length on this end.

**Comment by ManyTheFish** [comment]
closing in favor of #1480
