### ISSUE TITLE
Wrong nbHits when using distinct attribute

### ISSUE THREAD

**Issue by bsurai** [meilisearch/meilisearch#2152]
There's an example in meilisearch documentation https://docs.meilisearch.com/reference/features/distinct.html#example

As shown below, the dataset contains three documents representing different versions of a Lee jeans leather jacket.
```
[
  {
    "id": 1,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "brown",
    "product_id": "123456"
  },
  {
    "id": 2,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "black",
    "product_id": "123456"
  },
  {
    "id": 3,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "blue",
    "product_id": "123456"
  }
]
```
After setting the distinct attribute (`product_id`), querying for lee leather jacket would only return the first document found. 
```
{
  "hits": [
    {
      "id": 1,
      "description": "Leather jacket",
      "brand": "Lee jeans",
      "color": "brown",
      "product_id": "123456"
    }
  ],
  "offset": 0,
  "limit": 20,
  "nbHits": 1,
  "exhaustiveNbHits": false,
  "processingTimeMs": 0,
  "query": "lee leather jacket"
}
```
Example shows `nbHits: 1` is expected. I agree with that `nbHits` value. Nevertheless in our project it returns `nbHits: 3`, it counts every document from the dataset.

Meilisearch versions: 0.22.0, 0.25.2

P.S.  Facet distribution counts every document from the dataset (3 rather than 1), despite there's a distinct attribute.

**Comment by curquiza** [comment]
Hello @bsurai 
thanks for your report, we will investigate on it

**Comment by MarinPostma** [comment]
I have opened a pr on milli's side to fix that, it should make it to 0.27.0

**Comment by curquiza** [comment]
Reopening since it's not introduced in meilisearch yet.

Still need to
- release milli
- update the milli version on meilisearch side.

**Comment by curquiza** [comment]
Fixed by #2321

**Comment by paraboul** [comment]
Hey,

Confirming [#232](https://github.com/meilisearch/milli/pull/489) fixes the issue.

However count numbers are still wrong in `facetsDistribution` count (still doesn't dedup from distinct entries) but **only** if there are no filter set in the query.

 Should I open a new issue for that one?

**Comment by curquiza** [comment]
Hello @paraboul 

I've tried with the following documents

```json
[
  {
    "id": 1,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "brown",
    "product_id": "123456"
  },
  {
    "id": 2,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "black",
    "product_id": "123456"
  },
  {
    "id": 3,
    "description": "Leather jacket",
    "brand": "Lee jeans",
    "color": "blue",
    "product_id": "123456"
  }
]
```

and the following settings:
```json
{
  "distinctAttributes": "product_id",
  "filterableAttributes": "brand"
}
```
and I get this with this search: `{ "facetsDistribution": ["brand"] }`

```json
{
    "hits": [
        {
            "id": 1,
            "description": "Leather jacket",
            "brand": "Lee jeans",
            "color": "brown",
            "product_id": "123456"
        }
    ],
    "nbHits": 1,
    "exhaustiveNbHits": false,
    "query": "",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 1,
    "facetsDistribution": {
        "brand": {
            "Lee jeans": 1
        }
    },
    "exhaustiveFacetsCount": false
}
```

Could you please open [a new issue](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=) with detailed steps so that we can reproduce it? It would be really helpful to fix this bug

**Comment by bsurai** [comment]
@curquiza Thank you.

I've tested on v0.27.1. As I see, there's still some issue:
- It works well for relatively small search results (less then 40-50 distinct documents). 
- Though, if there're 100+ distinct documents in search result I get a wrong number of distinct documents, returns number of all documents instead of number of unique (distinct) documents.
- When I use offset (and limit) to get the latest documents in search results, I see the proper count of distinct documents.

My parameters:
- 1000+ distinct (unique) documents in a dataset. Every distinct document has 2-3 variations. So, the dataset may contain 2000+ documents.
- searching by filters may return 100+ distinct (unique) documents.
- limit = 36 documents per search.

**Comment by curquiza** [comment]
Hello @bsurai can you open [an issue](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=) please with an example, please?

>  I get a wrong number of distinct documents, returns number of all documents instead of number of unique (distinct) documents.

We need the number you expect, the number you get, and if possible a sample of your dataset. It would be definitely helpful to reproduce your issue.
If you are not comfortable showing even a piece of your datasets, you can send it by email!

Thanks again for your help, it is definitely help us improving the project 😄

**Comment by paraboul** [comment]
@curquiza I still have to find how to reproduce this easily but I'm seeing the same things as @bsurai

**Comment by curquiza** [comment]
Ok, let us know (by opening a new issue) if you have found a way to reproduce. Sorry for the bug, and thanks a lot for your report and help 🙏

**Comment by bsurai** [comment]
@curquiza I have to create a test case, because I'm not allowed to expose our product details.

**Comment by bsurai** [comment]
@curquiza I've created a new repository contain dataset, meilisearch settings, test case and screenshots.

**Comment by curquiza** [comment]
Thank you so much @bsurai 
We'll dig into it asap!
Thanks again for making us improve Meilisearch

**Comment by lebadapetru** [comment]
Hey there, facing the same issue here, any updates on the fix?

**Comment by curquiza** [comment]
Hello @lebadapetru 
what is your version? if it's v0.28.1, can you open another issue with detailed steps so that we can reproduce it? We fixed this specific problem some months ago.
