### ISSUE TITLE
Error: Meilisearch (v0.27.1) failed to infer the version of the database. Please consider using a dump to load your data

### ISSUE THREAD

**Issue by gekkota** [meilisearch/meilisearch#2503]
**Describe the bug**
Error: Meilisearch (v0.27.1) failed to infer the version of the database. Please consider using a dump to load your data

**To Reproduce**

With docker configuration. 

Destroyed the existing containers (0.26.0) and volumes and rebuilt them. 

Tried updating to 0.27.1 too which supposedly fixes the issue, but it didn't. 

Said same error but with version 0.27.1 instead of 0.26.0
New

Also destroyed the container / volume after doing the upgrade too and tried it again and it didn't make a difference

Changed the db folder path to /home/meili/data.ms too (or something similar) and that didn't work either

**Comment by curquiza** [comment]
Hello @gekkota what is exactly your docker command?

**Comment by curquiza** [comment]
Sorry I was expecting the docker command you use to run Meilisearch like

```bash
docker run -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v0.27.2  meilisearch --master-key=XXX
```

We did breaking changes regarding the mounted volumes on docker, this is maybe related
https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0 

Also, are you using the latest [meilisearch-Kubernetes](https://github.com/meilisearch/meilisearch-kubernetes) manifest?

**Comment by collins0492** [comment]
I had the same error with using Meilisearch image in AKS. I'm using v0.26.0 but I had it with all other versions too. My theory is that Meilisearch cannot initialise its database inside a persistent volume in AKS. To get it working:
* Spin up kubernetes stack with the volume mountPath as `/data.ms.tmp`. This allowed Meilisearch to create its database files in default location `/data.ms`
* SSH onto the Meilisearch pod `kubectl exec -it <pod> -- sh` and copy the contents of `/data.ms` to `/data.ms.tmp`
* Change the mountPath of the volume back to `/data.ms` and redeploy

This was the only way I could a get persistent volume to work with Meilisearch and AKS

**Comment by curquiza** [comment]
Hello @collins0492 
We had issues with Docker + kubernetes + Meilisearch we fixed in [v0.27.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0)

Sorry for the inconvenience and thanks for sharing your fix!

**Comment by miguelmoreba** [comment]
Hi, I am using v0.27.1 and still facing this issue. I am currently using the fix @collins0492 facilitated above.

Running on EKS

**Comment by deshetti** [comment]
Same with me both on v0.27.1 & v0.27.2 on GKE. Thanks to @collins0492, it works fine for me with the workaround. I still do not understand, how copying `/data.ms` to `/data.ms.tmp` and deleting `/data.ms.tmp` would make any difference? Doesn't it just end up with whatever `/data.ms` had in the first place?

Regardless, btw @collins0492 @miguelmoreba & me, we could confirm the issue persists in AKS, EKS & GKE. So, it might be safe to confirm that it is an issue with all the managed Kubernetes environments.

**Comment by curquiza** [comment]
Are you using [meilisearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes)?

Also, did you get the issue when you tried to pass from an older version to v0.27, or is it the first time you you set up Meilisearch with K8s?
Because the mount volume path changed in v0.27.0 as I explained [here](https://github.com/meilisearch/meilisearch/issues/2503#issuecomment-1151390346). You can check the [release changelogs](https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0).

**Comment by miguelmoreba** [comment]
I am using `meilisearch-kubernetes`
In my case is a fresh install of v0.27.1
I am aware that the volume path had changed, so I can confirm I'm mounting the PVC to the correct path. My high level understanding of what is happening is:

- Container creates initial DB files into /meili_data/data.ms
- PVC is mounted at /meili_data/data.ms (PVC is empty at this point)
- Meilisearch tries to access newly created db files at /meili_data/data.ms, but finds nothing and throws `error failed to infer the version of the database`

Thanks for the responses :)

**Comment by curquiza** [comment]
@alallema is meilisearch-kebernetes well compatible with v0.27.0?

**Comment by deshetti** [comment]
> Are you using [meilisearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes)?
> 
> Also, did you get the issue when you tried to pass from an older version to v0.27, or is it the first time you you set up Meilisearch with K8s? Because the mount volume path changed in v0.27.0 as I explained [here](https://github.com/meilisearch/meilisearch/issues/2503#issuecomment-1151390346). You can check the [release changelogs](https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0).

Nope. We had to create our own helm chart to support this and a few other features the current helm chart doesn't support like setting the master key from a secret: https://github.com/factly/helm-charts/tree/main/charts/meilisearch

**Comment by deshetti** [comment]
@miguelmoreba I already changed the mount path to the correct location and was still facing the issue: https://github.com/factly/helm-charts/blob/main/charts/meilisearch/values.yaml#L116

**Comment by miguelmoreba** [comment]
Running a fresh installation, I just:
- set the '`mountPath` to `meili_data` as per @curquiza 
- created a meilisearch index
- added some data
- took the statefulSet down
- re-applied manifest through kubectl

And the data persisted. So this seems to solve the issue for me!
Thanks :)

**Comment by curquiza** [comment]
A PR has been done on meilisearch-kubernetes -> https://github.com/meilisearch/meilisearch-kubernetes/pull/123
Looks like the solution is to set the `mountPath` to `meili_data`, it's not related to Meilisearch but to the kubernetes set up.

I close this issue, then.

Feel free to open a discussion [here](https://github.com/meilisearch/meilisearch/discussions) if you need support. You can also join [our Slack](https://meilicommunity.slack.com/ssb/redirect).
If you use [meilisearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes), you can also directly [open an issue in the repo](https://github.com/meilisearch/meilisearch-kubernetes/issues/new/choose).
