### ISSUE TITLE
internal: Missing key in the documents database

### ISSUE THREAD

**Issue by thijndehaas** [meilisearch/meilisearch#2945]
**Describe the bug**
After a while we get this message for all tasks: `internal: Missing key in the documents database..`.

**Meilisearch version:** v0.29.1

Current tasks counts:
Failed: 5.412 | Succeeded: 2.363`

I can clear the entire data.ms folder and run my indexation script multiple times with 0 failed tasks but then this error starts after a while.

This happens with delete and update tasks:

```php
Array
(
    [uid] => 7774
    [indexUid] => indexname
    [status] => failed
    [type] => documentDeletion
    [details] => Array
        (
            [receivedDocumentIds] => 1426
            [deletedDocuments] => 0
        )

    [error] => Array
        (
            [message] => internal: Missing key in the documents database..
            [code] => internal
            [type] => internal
            [link] => https://docs.meilisearch.com/errors#internal
        )

    [duration] => PT0.160491396S
    [enqueuedAt] => 2022-10-22T08:19:05.606566512Z
    [startedAt] => 2022-10-22T08:19:05.630546984Z
    [finishedAt] => 2022-10-22T08:19:05.79103838Z
)
```

```php
Array
(
    [uid] => 7773
    [indexUid] => indexname
    [status] => failed
    [type] => documentAdditionOrUpdate
    [details] => Array
        (
            [receivedDocuments] => 6380
            [indexedDocuments] => 0
        )

    [error] => Array
        (
            [message] => internal: Missing key in the documents database..
            [code] => internal
            [type] => internal
            [link] => https://docs.meilisearch.com/errors#internal
        )

    [duration] => PT0.030365691S
    [enqueuedAt] => 2022-10-22T08:19:05.5930828Z
    [startedAt] => 2022-10-22T08:19:05.599227896Z
    [finishedAt] => 2022-10-22T08:19:05.629593587Z
)
```

I wonder what this error means. It might be related to:
https://github.com/meilisearch/meilisearch-php/issues/401

---

EDIT by @curquiza 

- [ ] Implement changes in [Milli](https://github.com/meilisearch/milli/)
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `release-v0.30.3`

**Comment by oluademola** [comment]
Hello @thijndehaas 

Sorry for the inconvenience. 

Unfortunately, I am unable to reproduce this problem. Apart from deleting or posting documents via the add or update route, are there any steps you took not mentioned in the issue description that might help me reproduce this problem?

**Comment by thijndehaas** [comment]
Not really, the strange thing is I can create the index and index all data without any failure. Then I can send all data another time and still no failure. It starts bugging after a while.
I'm running the same configuration for 3 webshops now (on 3 different servers) and they all have the same problem.

Something strange is that even the complete reindex script has this problem after a while. And after a failed task a another task can succeed.

Task 7510 fails and 7511 succeeds:
```json
[
    {
        "uid": 7511,
        "indexUid": "indexname",
        "status": "failed",
        "type": "documentAdditionOrUpdate",
        "details": {
            "receivedDocuments": 2775,
            "indexedDocuments": 0
        },
        "error": {
            "message": "internal: Missing key in the documents database..",
            "code": "internal",
            "type": "internal",
            "link": "https://docs.meilisearch.com/errors#internal"
        },
        "duration": "PT0.052535142S",
        "enqueuedAt": "2022-11-01T12:18:07.42112152Z",
        "startedAt": "2022-11-01T12:18:07.422249286Z",
        "finishedAt": "2022-11-01T12:18:07.474784428Z"
    },
    {
        "uid": 7510,
        "indexUid": "indexname",
        "status": "failed",
        "type": "documentAdditionOrUpdate",
        "details": {
            "receivedDocuments": 7400,
            "indexedDocuments": 0
        },
        "error": {
            "message": "internal: Missing key in the documents database..",
            "code": "internal",
            "type": "internal",
            "link": "https://docs.meilisearch.com/errors#internal"
        },
        "duration": "PT0.081773778S",
        "enqueuedAt": "2022-11-01T12:18:02.612261086Z",
        "startedAt": "2022-11-01T12:18:02.612654709Z",
        "finishedAt": "2022-11-01T12:18:02.694428487Z"
    }
]
```

@oluademola Do you know what this error exactly means? Maybe I can debug my data based on the error.

Can this have something to do with our documents not having complete numeric ids?
We have something like this structure SHOPID_ITTEMID:
```
10-1391
10-5939
51-12393
```

**Comment by oluademola** [comment]
Hi @thijndehaas,

I see no problem with that. If the id is a string, it permits alphanumeric characters, hyphens, and underscores.

**Comment by thijndehaas** [comment]
Maybe this is related to:
https://github.com/meilisearch/meilisearch/issues/3021
We also had the problem with duplicate documents, maybe duplicate or soft deleted documents give this failure.

**Comment by curquiza** [comment]
Thanks for the report, considering this now as a bug to fix for v0.30.0 if possible

**Comment by Kerollmops** [comment]
> Maybe this is related to:
> https://github.com/meilisearch/meilisearch/issues/3021
> Maybe this is related to: #3021 We also had the problem with duplicate documents, maybe duplicate or soft deleted documents give this failure.

Indeed, thank you for this very important information. If this internal error is triggered on an instance that also returns duplicated documents it can highly indicate that it is related to a bug in the indexing part of the engine and more specifically when storing the soft deleted documents ids.

We will continue this investigation next week, we have a lot more information to work with now, and the fix is in a good way to land for v0.30.0 🤞

**Comment by Kerollmops** [comment]
This PR should be fixed by https://github.com/meilisearch/milli/pull/690.

**Comment by curquiza** [comment]
Closed by #3036

**Comment by thijndehaas** [comment]
Wanted to report that this is still happening on 0.30.1 with multiple clean installations.

Server A: [Statuses] Failed: 1.349 | Succeeded: 1.546
Server B: [Statuses] Failed: 547 | Succeeded: 1.284
Server C: [Statuses] Succeeded: 1.281 | Failed: 106

This happens with additions and deletes:
```php
[6] => Array
        (
            [uid] => 1466
            [indexUid] => indexname
            [status] => failed
            [type] => documentDeletion
            [canceledBy] => 
            [details] => Array
                (
                    [providedIds] => 100000
                    [deletedDocuments] => 0
                )

            [error] => Array
                (
                    [message] => internal: Missing key in the documents database..
                    [code] => internal
                    [type] => internal
                    [link] => https://docs.meilisearch.com/errors#internal
                )

            [duration] => PT0.085360497S
            [enqueuedAt] => 2022-12-08T14:13:29.020043761Z
            [startedAt] => 2022-12-08T14:13:30.679561564Z
            [finishedAt] => 2022-12-08T14:13:30.764922061Z
        )

    [7] => Array
        (
            [uid] => 1465
            [indexUid] => indexname
            [status] => failed
            [type] => documentAdditionOrUpdate
            [canceledBy] => 
            [details] => Array
                (
                    [receivedDocuments] => 2338
                    [indexedDocuments] => 0
                )

            [error] => Array
                (
                    [message] => internal: Missing key in the documents database..
                    [code] => internal
                    [type] => internal
                    [link] => https://docs.meilisearch.com/errors#internal
                )

            [duration] => PT0.041687729S
            [enqueuedAt] => 2022-12-08T14:13:28.956479898Z
            [startedAt] => 2022-12-08T14:13:30.606847773Z
            [finishedAt] => 2022-12-08T14:13:30.648535502Z
        )
```

**Comment by curquiza** [comment]
Hello @thijndehaas, can you share your documents and the settings of your Meilisearch instance?
Also, did you correctly erase your data.ms before using v0.30.1? You need to re-import your data since the database can be corrupted because of the bug in v0.30.0

**Comment by thijndehaas** [comment]
Yes I always completely remove all data when I update, with:
```bash
cd /home/meilisearch
wget https://github.com/meilisearch/meilisearch/releases/download/v0.30.1/meilisearch-linux-amd64
mv meilisearch-linux-amd64 meilisearch
chmod +x meilisearch
supervisorctl stop meilisearch
mv data.ms data.ms.remove
supervisorctl start meilisearch

```

# INFO
Start command:
```bash
/home/meilisearch/meilisearch --http-addr=127.0.0.1:7700 --env=production --db-path=/home/meilisearch/data.ms --master-key=TOKEN_HERE --max-indexing-threads=20 --max-indexing-memory=50Gb
```

Index data:
```bash
curl -X GET 'localhost:7700/indexes/INDEX_NAME' -H 'Authorization: Bearer TOKEN_HERE';
```

```json
{"uid":"INDEX_NAME","createdAt":"2022-12-07T13:08:24.54570964Z","updatedAt":"2022-12-08T16:39:11.980485015Z","primaryKey":"id"}#
```

Version:
```bash
curl -X GET 'localhost:7700/version' -H 'Authorization: Bearer TOKEN_HERE';
```

```json
{"commitSha":"58cd5d29e8a8c5ccece6a4597bcaa92fd6b10081","commitDate":"2022-12-06T16:22:38Z","pkgVersion":"0.30.1"}#
```

Index settings:
```bash
curl -X GET 'localhost:7700/indexes/INDEX_NAME/settings' -H 'Authorization: Bearer TOKEN_HERE';
```

```json
{"displayedAttributes":["*"],"searchableAttributes":["name","search_name","description","eans"],"filterableAttributes":["brand","categories","colors","discount","genders","master_categories","materials","price_for","sizes","sub_categories"],"sortableAttributes":["added","boost","discount","price_for","shop_count"],"rankingRules":["typo","words","proximity","attribute","sort","exactness","shop_sort_count:desc","added:desc"],"stopWords":["de","deze","dit","een","heeft","het","in","is","the"],"synonyms":{},"distinctAttribute":null,"typoTolerance":{"enabled":true,"minWordSizeForTypos":{"oneTypo":5,"twoTypos":9},"disableOnWords":[],"disableOnAttributes":[]},"faceting":{"maxValuesPerFacet":99999},"pagination":{"maxTotalHits":99999999}}#
```

Example documents:
```bash
curl -X POST 'http://localhost:7700/indexes/INDEX_NAME/search' -H 'Authorization: Bearer TOKEN_HERE' -H 'Content-Type: application/json' --data-binary '{ "q": "", "limit": 2 }'
```

```json
{"hits":[{"name":"Lina Locchi Enkellaarsjes Dames Laarzen Damesschoenen L1281 Lood","search_name":"lina locchi dames enkellaarsjes laarzen damesschoenen l1281 lood","description":"Lina Locchi Dames EnkellaarsjesLina Locchi Dames EnkellaarsjesEnkellaarsjes","eans":["8720699216576","8720699216583","8720699216590","8720699216606","8720699216613","8720699216620","8720699216637"],"id":"2-124217","added":1670371200,"boost":5,"image":"/images/products/bolcom/lina-locchi-enkellaarsjes-dames-laarzen-damesschoenen-l1281-lood-719260.jpg","shop_count":3,"shop_sort_count":3,"shop_name":"3 webshops","url":"/product/lina-locchi-dames-enkellaarsjes-2-124217","genders":["Dames"],"colors":[],"materials":[],"master_categories":[],"categories":["enkellaarsjes"],"sub_categories":[],"brand":"Lina Locchi","sizes":["36","37","38","39","40","41","42"],"price_for":139.95,"price_from":0,"discount":0,"updated":1670516887},{"name":"Lina Locchi Enkellaarsjes Dames Laarzen Damesschoenen L1281 Goud","search_name":"lina locchi dames enkellaarsjes laarzen damesschoenen l1281 goud","description":"Lina Locchi Dames EnkellaarsjesLina Locchi Dames EnkellaarsjesEnkellaarsjes","eans":["8720699216507","8720699216514","8720699216521","8720699216538","8720699216545","8720699216552","8720699216569"],"id":"2-124208","added":1670371200,"boost":5,"image":"/images/products/bolcom/lina-locchi-enkellaarsjes-dames-laarzen-damesschoenen-l1281-goud-719496.jpg","shop_count":3,"shop_sort_count":3,"shop_name":"3 webshops","url":"/product/lina-locchi-dames-enkellaarsjes-2-124208","genders":["Dames"],"colors":["goud"],"materials":[],"master_categories":[],"categories":["enkellaarsjes"],"sub_categories":[],"brand":"Lina Locchi","sizes":["36","37","38","39","40","41","42"],"price_for":139.95,"price_from":0,"discount":0,"updated":1670516887}],"query":"","processingTimeMs":1,"limit":2,"offset":0,"estimatedTotalHits":576174}#
```

**Comment by loiclec** [comment]
Hi Thijn,

**Comment by loiclec** [comment]
Hi Thijn,
Indeed, the bug is still present. Thanks a lot for reporting it to us again. In the past couple of weeks, we fixed two mistakes that could cause the `Missing key in the documents database` internal error to be thrown, but it appears that we still missed one mistake 😞 A new fix is nearly ready and will be released shortly. We are also taking steps to ensure that this mistake does not happen again by writing more intensive tests.

**Comment by curquiza** [comment]
Thanks lo for the information!

This will be fixed in v0.30.3 version we will release by the end of the week
Thanks for reporting

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3248
Will be released in v0.30.3 by the end of the week
