### ISSUE TITLE
HuggingFace embeddings fails

### ISSUE THREAD

**Issue by scottaglia** [meilisearch/meilisearch#4271]
**Describe the bug**
The upload of documents to an index where HuggingFace embedders is enabled fails. When uploading the documents the server logs:

```
[2023-12-19T18:27:28Z INFO  hf_hub] Token file not found "/root/.cache/huggingface/token"
```

and the task fails with the following error message:
```
      "error": {
        "message": "internal: Error while generating embeddings: error: fetching file from HG_HUB failed: request error: https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/617ca489d9e86b49b8167676d8220688b99db36e/config.json: status code 404.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
      },
```

**To Reproduce**
1. `docker run -it --rm -p 7700:7700 -v `pwd`:/meili_data getmeili/meilisearch:v1.6.0-rc.1`
2. Enable vectorStore
```bash
curl \
-X PATCH 'http://localhost:7700/experimental-features/' \
-H 'Content-Type: application/json'  \
--data-binary '{"vectorStore": true}'
```
3. Create index with the embedder:
```bash
curl \
-X PATCH 'http://localhost:7700/indexes/products/settings' \
-H 'Content-Type: application/json' --data-binary \
'{ "embedders": { "default": { "source": { "huggingFace": { "model": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" } }, "documentTemplate": { "template": "A product titled '{{doc.title}}'"} } } }'
```

**Meilisearch version:**
v1.6.0-rc.1

**Comment by dureuill** [comment]
Hello 👋 

Thank you for the report :heart: 

I can confirm this is indeed a bug affecting v1.6.0-rc.1 😞

Currently you can workaround it by passing an explicit additional `revision` field to the `huggingFace` object:

```sh
 curl \
-X PATCH 'http://localhost:7700/indexes/products/settings' \
-H 'Content-Type: application/json' --data-binary \
'{ 
  "embedders": { 
    "default": {
      "source": {
        "huggingFace": {
          "model": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2", 
          "revision": "a9c555277f9bcf24f28fa5e092e665fc6f7c49cd" 
        } 
      }, 
      "documentTemplate": { "template": "A product titled '{{doc.title}}'"}
    } 
  } 
}'
```

I'm on it to fix it so this is not necessary anymore 👍

**Comment by curquiza** [comment]
Fixed by #4272 and integrated into v1.6.0-rc.2 I will create in a few hours.

**Comment by anaibol** [comment]
I'm still having this issue on v.1.6.2: Token file not found "/root/.cache/huggingface/token"
Are there some token declaration requirements?

**Comment by dureuill** [comment]
Hello @anaibol :wave:

Thank you for your report, can you be more specific as to what you are prevented from doing?

The message you're reporting is a warning, and is expected if you didn't manually set a Hugging Face token in the described location.

A Hugging Face token is only required to download specific models from Hugging Face. In particular, the model Meilisearch uses by default doesn't require a token, so embedding should work even in presence of this warning.

So I have a few questions for clarification:

1. Can you share your embedder settings?
2. Are you seeing an issue with embedding, such as a failed indexing task in the task queue. If so, can you show the relevant part of the task queue?
3. Are you requesting a model that requires a token?
4. If so, did you try putting the token at the described location?
